<?xml version="1.0"?>
<robot  xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:macro name="roue" params="suffix num xx zz sign">
   <link name="$(arg namespace)/${suffix}_wheel_link_${num}">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="white"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
           <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <xacro:cylinder_inertia m="100" r="${wheel_radius}" h="${wheel_width}"/> 
    </link>

    <joint name="$(arg namespace)/${suffix}_wheel_joint_${num}" type="continuous">
        <parent link="$(arg namespace)/${suffix}_track"/>
        <child link="$(arg namespace)/${suffix}_wheel_link_${num}"/>
        <origin xyz="${xx} ${sign}${wheel_ygap} ${wheel_radius+zz}" rpy="0 0 0"/>
        <limit effort="0" velocity="1.0"/>
        <axis xyz="0 1 0"/>
    </joint> 

    <gazebo reference="$(arg namespace)/${suffix}_wheel_link_${num}">
      <mu1>10</mu1>
      <mu2>10</mu2>
      <!-- <damping>0.1</damping> -->
    <material>Gazebo/Black</material>
  </gazebo>

</xacro:macro>



</robot>