<?xml version="1.0" ?>
<!-- <robot name="robot_namespace" value="/$(arg namespace)" xmlns:xacro="http://ros.org/wiki/xacro"> -->
<robot name="bunker1" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="namespace" default=""/>
    <xacro:include filename="inertial.xacro"/>
    <xacro:include filename="material.xacro"/>
    <xacro:include filename="macro-roue.xacro"/>
    <xacro:include filename="macro-imu.xacro"/>    
    <xacro:include filename="macro-gps2.xacro"/>  
    <!-- <xacro:include filename="macro-d435.xacro"/>  -->
    <xacro:include filename="macro-camera-perception.xacro"/> 


    <xacro:property name="base_width" value="0.350"/>
    <xacro:property name="base_length" value="0.560"/>
    <xacro:property name="base_height" value="0.22"/>
    <xacro:property name="sol_height" value="0.08"/>

    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="wheel_ygap" value="${base_width*0.6+wheel_width/2.0}"/>
<!-- position des roues -->
    <xacro:property name="x1" value="${wheel_radius*0.9}"/>
    <xacro:property name="x2" value="${wheel_radius*1.85}"/>
    <xacro:property name="x3" value="0.254"/>
    <xacro:property name="x4" value="0.300"/>
    <xacro:property name="x5" value="0.242"/>

 

    <link name="$(arg namespace)/base_link">
        <origin xyz="0 0 0.5" rpy="0 0 0"/>
    </link>
    <link name="$(arg namespace)/base_footprint">
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
    </link>
    <joint name="$(arg namespace)/base_footprint_joint" type="fixed">
        <parent link="$(arg namespace)/base_link"/>
        <child link="$(arg namespace)/base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <joint name="$(arg namespace)/corps_joint" type="fixed">
        <parent link="$(arg namespace)/base_link"/>
        <child link="$(arg namespace)/corps_link" />
        <origin xyz="0 0 ${base_height/2+sol_height}" rpy="0 0 0"/>
    </joint>

    <link name="$(arg namespace)/corps_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>            
            </geometry>

        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width}  ${base_height}"/>  
            </geometry>
        </collision>

        <xacro:box_inertia m="50.0" d="${base_width}" w="${base_length}" h="${base_height}"/> 
    </link>    

<!-- LEFT TRACK  -->
    <link name='$(arg namespace)/left_track'>
        <origin xyz="0 0.2 0" rpy="0 0 0"/>
        <xacro:box_inertia m="1.0" w="${base_width}" d="${base_length}" h="${base_height}"/> 

    </link>

    <joint name='$(arg namespace)/left_track_j' type='revolute'>
        <child link="$(arg namespace)/left_track"/>
        <parent link="$(arg namespace)/base_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="0" velocity="4"/>
        <!-- <use_parent_model_frame>1</use_parent_model_frame> -->
    </joint>            
<!-- RIGHT TRACK  -->
    <link name='$(arg namespace)/right_track'>
        <origin xyz="0 -0.2 0" rpy="0 0 0"/>
            <xacro:box_inertia m="1.0" w="${base_width}" d="${base_length}" h="${base_height}"/> 

    </link>
    <joint name='$(arg namespace)/right_track_j' type='revolute'>
        <child link="$(arg namespace)/right_track"/>
        <parent link="$(arg namespace)/base_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="0" effort="0" velocity="4"/>
        <use_parent_model_frame>1</use_parent_model_frame>
    </joint>            


<!-- LEFT WHEELs -->

<!-- <xacro:roue suffix="left" num="0" xx="0" zpol_bunker/urdf/macro-camera.xacroz="0" sign=""/> 
<xacro:roue suffix="left" num="1" xx="${x1}" zz="0" sign=""/> 
<xacro:roue suffix="left" num="2" xx="${-x1}" zz="0" sign=""/>  -->
<xacro:roue suffix="left" num="3" xx="${x2}" zz="0" sign=""/> 
<xacro:roue suffix="left" num="4" xx="${-x2}" zz="0" sign=""/> 
<!-- <xacro:roue suffix="left" num="5" xx="${-x3}" zz="0.120" sign=""/> 
<xacro:roue suffix="left" num="6" xx="${x4}" zz="0.155" sign=""/> 
<xacro:roue suffix="left" num="7" xx="${x5}" zz="0.078" sign=""/>  -->


<!-- RIGHT WHEELs -->
<!-- <xacro:roue suffix="right" num="0" xx="0" zz="0" sign="-"/> 
<xacro:roue suffix="right" num="1" xx="${x1}" zz="0" sign="-"/> 
<xacro:roue suffix="right" num="2" xx="${-x1}" zz="0" sign="-"/>  -->
<xacro:roue suffix="right" num="3" xx="${x2}" zz="0" sign="-"/> 
<xacro:roue suffix="right" num="4" xx="${-x2}" zz="0" sign="-"/> 
<!-- <xacro:roue suffix="right" num="5" xx="${-x3}" zz="0.120" sign="-"/> 
<xacro:roue suffix="right" num="6" xx="${x4}" zz="0.155" sign="-"/> 
<xacro:roue suffix="right" num="7" xx="${x5}" zz="0.078" sign="-"/>  -->


<!-- IMU -->
<xacro:myimu xyz="0 0 ${sol_height+base_height}" rpy="0 0 0"/>

<!-- GPS -->
<!-- <xacro:mygps xyz="0.1 0 ${sol_height+base_height+0.05}" rpy="0 0 0"/> -->

<!-- CAM -->
<!-- <xacro:camera num="1" xyz="${base_length/2} 0.0 ${base_height+sol_height+0.0125}" rpy="0 0 0"/> -->
<xacro:camera num="1" xyz="0.0 0.0 0.3" rpy="0 0 0"/>

<!-- pour republier les angles de roues -->
<gazebo>

    <plugin name="wheel_drive_controller" filename="libgazebo_ros_diff_drive.so">


    <!-- wheels -->
    <num_wheel_pairs>2</num_wheel_pairs>
                <!-- <left_joint>$(arg namespace)/left_wheel_joint_0</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_0</right_joint>  
                <left_joint>$(arg namespace)/left_wheel_joint_1</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_1</right_joint>
                <left_joint>$(arg namespace)/left_wheel_joint_2</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_2</right_joint> -->
                <left_joint>$(arg namespace)/left_wheel_joint_3</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_3</right_joint>
                <left_joint>$(arg namespace)/left_wheel_joint_4</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_4</right_joint>
                <!-- <left_joint>$(arg namespace)/left_wheel_joint_5</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_5</right_joint>
                <left_joint>$(arg namespace)/left_wheel_joint_6</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_6</right_joint>
                <left_joint>$(arg namespace)/left_wheel_joint_7</left_joint>
                <right_joint>$(arg namespace)/right_wheel_joint_7</right_joint> -->




    <!-- kinematics -->
    <wheel_separation>${wheel_ygap*2.0}</wheel_separation>
    <wheel_diameter>${wheel_radius*2.0}</wheel_diameter>
    <max_wheel_torque>20000.0</max_wheel_torque>
    <max_wheel_acceleration>10.0</max_wheel_acceleration>

    <!-- odometry  --> 
    <!-- <odometry_source>world</odometry_source> -->
    <odometry_frame>$(arg namespace)/odom</odometry_frame>
    <robot_base_frame>$(arg namespace)/base_link</robot_base_frame>


    <publish_odom>true</publish_odom>
    <publish_odom_tf>true</publish_odom_tf>
    <update_rate>100.0</update_rate>
    </plugin>
    
</gazebo>


<gazebo reference="$(arg namespace)/corps_link">

    <material>Gazebo/Red</material>
  </gazebo>


</robot>
